Update create_certs.yml

diff --git a/.github/workflows/create_certs.yml b/.github/workflows/create_certs.yml
--- a/.github/workflows/create_certs.yml
+++ b/.github/workflows/create_certs.yml
@@ -80,40 +80,40 @@ jobs:
         run: |
           echo "ENABLE_NUKE_CERTS=[${{ vars.ENABLE_NUKE_CERTS }}]"
           echo "FORCE_NUKE_CERTS=[${{ vars.FORCE_NUKE_CERTS }}]"
-          
-- name: Set output and annotations based on Fastlane result
-  id: set_output
-  env:
-    ENABLE_NUKE_CERTS: ${{ vars.ENABLE_NUKE_CERTS }}
-    FORCE_NUKE_CERTS: ${{ vars.FORCE_NUKE_CERTS }}
-  run: |
-    echo "DEBUG: ENABLE_NUKE_CERTS=[$ENABLE_NUKE_CERTS]"
-    echo "DEBUG: FORCE_NUKE_CERTS=[$FORCE_NUKE_CERTS]"
+        
+      - name: Set output and annotations based on Fastlane result
+        id: set_output
+        env:
+          ENABLE_NUKE_CERTS: ${{ vars.ENABLE_NUKE_CERTS }}
+          FORCE_NUKE_CERTS: ${{ vars.FORCE_NUKE_CERTS }}
+        run: |
+          echo "DEBUG: ENABLE_NUKE_CERTS=[$ENABLE_NUKE_CERTS]"
+          echo "DEBUG: FORCE_NUKE_CERTS=[$FORCE_NUKE_CERTS]"
 
-    CERT_STATUS_FILE="${{ github.workspace }}/fastlane/new_certificate_needed.txt"
+          CERT_STATUS_FILE="${{ github.workspace }}/fastlane/new_certificate_needed.txt"
 
-    if [ -f "$CERT_STATUS_FILE" ]; then
-      CERT_STATUS=$(cat "$CERT_STATUS_FILE" | tr -d '\n' | tr -d '\r')
-      echo "new_certificate_needed: $CERT_STATUS"
-      echo "new_certificate_needed=$CERT_STATUS" >> "$GITHUB_OUTPUT"
-    else
-      echo "Certificate status file not found. Defaulting to false."
-      CERT_STATUS="false"
-      echo "new_certificate_needed=false" >> "$GITHUB_OUTPUT"
-    fi
+          if [ -f "$CERT_STATUS_FILE" ]; then
+          CERT_STATUS=$(cat "$CERT_STATUS_FILE" | tr -d '\n' | tr -d '\r')
+          echo "new_certificate_needed: $CERT_STATUS"
+          echo "new_certificate_needed=$CERT_STATUS" >> "$GITHUB_OUTPUT"
+          else
+          echo "Certificate status file not found. Defaulting to false."
+          CERT_STATUS="false"
+          echo "new_certificate_needed=false" >> "$GITHUB_OUTPUT"
+          fi
 
-    if [ "$CERT_STATUS" != "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
-      echo "::notice::🔔 Automated renewal of certificates is disabled because ENABLE_NUKE_CERTS is not 'true'."
-    fi
+          if [ "$CERT_STATUS" != "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
+          echo "::notice::🔔 Automated renewal of certificates is disabled because ENABLE_NUKE_CERTS is not 'true'."
+          fi
 
-    if [ "$CERT_STATUS" = "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
-      echo "::error::❌ No valid distribution certificate found. Automated renewal of certificates was skipped because ENABLE_NUKE_CERTS is not 'true'."
-      exit 1
-    fi
+          if [ "$CERT_STATUS" = "true" ] && [ "$ENABLE_NUKE_CERTS" != "true" ]; then
+          echo "::error::❌ No valid distribution certificate found. Automated renewal of certificates was skipped because ENABLE_NUKE_CERTS is not 'true'."
+          exit 1
+          fi
 
-    if [ "$FORCE_NUKE_CERTS" = "true" ]; then
-      echo "::warning::‼️ Nuking of certificates was forced because FORCE_NUKE_CERTS is 'true'."
-    fi
+          if [ "$FORCE_NUKE_CERTS" = "true" ]; then
+          echo "::warning::‼️ Nuking of certificates was forced because FORCE_NUKE_CERTS is 'true'."
+          fi
           CERT_STATUS_FILE="${{ github.workspace }}/fastlane/new_certificate_needed.txt"
           ENABLE_NUKE_CERTS=${{ vars.ENABLE_NUKE_CERTS }}
           
